

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 9090